import contextlib
from typing import Iterator, Any

class LogContext(object):
    def __init__(self, verbosity: int = 0, indent_width: int = 2) -> None: ...
    def log(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def debug(self, *args: Any, **kwargs: Any) -> None: ...
    def info(self, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, *args: Any, **kwargs: Any) -> None: ...
    def error(self, *args: Any, **kwargs: Any) -> None: ...
    def _indent(self) -> None: ...
    def _dedent(self) -> None: ...
    @contextlib.contextmanager
    def indentation(self) -> Iterator[None]: ...

log: LogContext = ...
